// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent {
  //Atributo editoras que inicializa um vetor vazio.
  public editoras: Array<Editora> = [];
  //Atributo livros que inicializa um vetor vazio.
  public livros: Array<Livro> = [];

  //Serviços injetados através do construtor.
  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}
  //Método que preenche os vetores editoras e livros.
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros()
    .then(dados => {
      this.livros = dados;
    })
  }
  //Método excluir que chama servLivros.
  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo)
    .then(() => {
      return this.servLivros.obterLivros();
    })
    .then(dados => {
      this.livros = dados;
    })
  }
  //Método obterNome que chama servEditora.
  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container-fluid">
    <!--Título da página.-->
    <h1 class="my-3">
        Catálogo de livros
    </h1>
    <!--Tabela para exibição dos livros.-->
    <table class="table table-striped">
        <!--Cabeçalho da tabela.-->
        <thead>
            <!--Linha do cabeçalho.-->
            <tr>
                <!--Células do cabeçalho.-->
                <th class="bg-dark text-white col-2 p-2">Título</th>
                <th class="bg-dark text-white col-6 p-2">Resumo</th>
                <th class="bg-dark text-white col-2 p-2">Editora</th>
                <th class="bg-dark text-white col-2 p-2">Autores</th>
            </tr>
        </thead>
        <!--Corpo da tabela.-->
        <tbody>
            <!--Linha com laço para exibir cada livro do vetor livros.-->
            <tr *ngFor="let livro of livros">
                <!--Célula com título e botão para excluir o livro.-->
                <td class="d-flex flex-column">
                    {{livro.titulo}}
                    <button (click)="excluir(livro.codigo)" class="btn btn-danger mt-2">Excluir</button>
                </td>
                <!--Célula de resumo-->
                <td>{{livro.resumo}}</td>
                <!--Célula que invoca função obterNome.-->
                <td>{{obterNome(livro.codEditora)}}</td>
                <!--Célula para autores em forma de lista.-->
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{autor}}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import React, {useState, useEffect} from "react";

//Instâncias das classes.
const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

//Componente para a linha com informações do livro e botão de excluir.
function LinhaLivro (props) {
    const {livro, excluir} = props;
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);
    return (
        <tr>
            <td>
                <div className="d-flex flex-column">
                    <span>{livro.titulo}</span>
                    <button type="button" className="btn btn-danger col-md-6" onClick={() => excluir(livro.codigo)}>Excluir</button>
                </div>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>{livro.autores.map((autor, index) => (<li key = {index}>{autor}</li>))}</td>
        </tr>
    )
}

//Componente para exibir o catálogo de livros em uma tabela.
function LivroLista () {
    const [livros, setLivros] = useState ([]);
    const [carregado, setCarregado] = useState (false);
    useEffect (() => {
        if (!carregado){
            controleLivro.obterLivros()
            .then((livros) => {
                setLivros(livros);
                setCarregado(true);
            })
        }
    }, [carregado]);

    //Método para excluir o livro chamado pelo botão.
    const excluir = (codigo) => {
        controleLivro.excluir(codigo)
        .then(() => {
            setCarregado (false);
        })
    };

    //Retorna o nome da tabela, seu cabeçalho e os livros com botão de exclusão.
    return (
        <div className="container">
            <main>
                <h1 className="my-3">Catálogo de livros</h1>
                <table className="table table-striped">
                    <thead>
                        <tr>
                            <th className="bg-dark text-white col-2 text-left p-2">Título</th>
                            <th className="bg-dark text-white col-6 text-left p-2">Resumo</th>
                            <th className="bg-dark text-white col-2 text-left p-2">Editora</th>
                            <th className="bg-dark text-white col-2 text-left p-2">Autores</th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro, index) => (
                            <LinhaLivro key = {index} livro = {livro} excluir = {excluir}/>
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    )
}
export default LivroLista;
