// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent {
  //Atributo livro instanciado via construtor.
  public livro: Livro;
  //Atributo autoresForm que inicializa vazio.
  public autoresForm:string = "";
  //Atributo editoras que inicializa um vetor vazio.
  public editoras: Array<Editora> = [];

  //Serviços injetados através do construtor.
  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro("", 0, "", "", []);
  }
  //Método que preenche o vetor de editoras.
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }
  /*Método incluir que preenche o aributo autores e
  invoca incluir de controle-livros.service.*/
  incluir = (): void => {
    this.livro.autores = this.autoresForm.split("\n").filter(author => author.trim() !== '');
    this.servLivros.incluir(this.livro)
    .then(() => {
      this.router.navigateByUrl("/lista");
    })
  }
}

<main class="container-fluid">
    <!--Título da página.-->
    <h1 class="my-3">
        Dados do livro
    </h1>
    <!--Formulário.-->
    <form (submit)="incluir()" ngNativeValidate>
        <!--Área de título.-->
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" id="titulo" name="titulo" [(ngModel)]="livro.titulo" class="form-control" required>
        </div>
        <!--Área de resumo.-->
        <div class="mb-3">
            <label for="resumo" class="form-label">Resumo</label>
            <textarea id="resumo" name="resumo" [(ngModel)]="livro.resumo" class="form-control" ></textarea>
        </div>
        <!--Área de editora.-->
        <div class="mb-3">
            <label for="editora" class="form-label">Editora</label>
            <select id="editora" name="editora" [(ngModel)]="livro.codEditora" class="form-select" required>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{editora.nome}}</option>
            </select>
        </div>
        <!--Área de autores.-->
        <div class="mb-3">
            <label for="autores" class="form-label">Autores (1 por linha)</label>
            <textarea id="autores" name="autores" [(ngModel)]="autoresForm" class="form-control"></textarea>
        </div>
        <!--Botão para submissão.-->
        <button type="submit" class="btn btn-primary mb-3">Salvar dados</button>
    </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from "next";
import React, { useState } from "react";
import styles from '../styles/Home.module.css'
import ControleEditora from "@/classes/controle/ControleEditora";
import Livro from "@/classes/modelo/Livro";
import { Router, useRouter } from "next/router";
import { Menu } from "@/componentes/Menu";
import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.css';
import ControleLivro from "@/classes/controle/ControleLivros";

const controleEditora = new ControleEditora();
const controleLivro =  new ControleLivro();

const LivroDados: NextPage = () => {
    const opcoes = controleEditora.getEditoras().map((editora => ({
        value: editora.codEditora,
        text: editora.nome
    })))
    const [titulo, setTitulo] = useState<string>("");
    const [resumo, setResumo] = useState<string>("");
    const [autores, setAutores] = useState<string>("");
    const [codEditora, setCodEditora] = useState(opcoes[0].value);
    const router = useRouter();

    const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(Number(event.target.value));
    }
    const incluir = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        const livro: Livro = {
            codigo: "",
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n"),
            codEditora: codEditora
        }
        controleLivro.incluir(livro)
        .then(() => {
            router.push('/LivroLista');
        })
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Loja Next</title>
            </Head>
            <Menu />
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Dados do livro
                </h1>
                <form onSubmit={incluir}>
                    <div className="mb-3">
                        <label htmlFor="titulo" className="form-label">Título</label>
                        <input className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)}/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="resumo" className="form-label">Resumo</label>
                        <textarea className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)}/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="editora" className="form-label">Editora</label>
                        <select className="form-select" value={codEditora} onChange={tratarCombo}>
                            {opcoes.map(opcao => (
                                <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                            ))}
                        </select>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="autores" className="form-label">Autores (1por linha)</label>
                        <textarea className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)}/>
                    </div>
                    <div className="mb-3">
                        <button type="submit" className="btn btn-primary" >Salvar dados</button>
                    </div>
                </form>
            </main>
        </div>
    )
}

export default LivroDados;
