// clientes/livros-react/src/LivroDados.js
import { useState } from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";

//Instâncias das classes.
const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

//Componente para exibir o formulário para um novo livro.
function LivroDados () {
    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));
    //Propriedades de estados do livro.
    const [titulo, setTitulo] = useState ('');
    const [resumo, setResumo] = useState ('');
    const [autores, setAutores] = useState ('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    //Função de navegação do Hook.
    const navigate = useNavigate();

    //Função chamada para caixa de seleção das editoras no return.
    const tratarCombo = (evento) => {
        setCodEditora(Number(evento.target.value));
    };
    //Função chamada para enviar os dados das propriedades para a classe ControleLivro.
    const incluir = (evento) => {
        evento.preventDefault();
        const autoresArray = autores.split('\n');
        const novoLivro = {
            codigo: "",
            titulo: titulo,
            resumo: resumo,
            autores: autoresArray,
            codEditora: codEditora
        };
        controleLivro.incluir(novoLivro).then(() => {
            navigate("/");
        });
    };
    //Retorna o formulário em HTML.
    return (
        <main className="container">
            <div className="row">
                <h1 className="my-3">Dados do livro</h1>
                <form onSubmit={incluir}>
                    <div className="mb-3">
                        <label htmlFor="titulo" className="form-label">Título</label>
                        <input type="text" className="form-control" value={titulo} onChange={(e) => setTitulo(e.target.value)}/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="resumo" className="form-label">Resumo</label>
                        <textarea type="text" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)}/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="editora" className="form-label">Editora</label>
                        <select className="form-select" value={codEditora} onChange={tratarCombo}>
                            {opcoes.map(opcao => (
                                <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                            ))}
                        </select>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="autores" className="form-label">Autores (1por linha)</label>
                        <textarea type="text" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)}/>
                    </div>
                    <div className="mb-3">
                        <button type="submit" className="btn btn-primary" >Salvar dados</button>
                    </div>
                </form>
            </div>
        </main>
    );
}
export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent {
  //Atributo livro instanciado via construtor.
  public livro: Livro;
  //Atributo autoresForm que inicializa vazio.
  public autoresForm:string = "";
  //Atributo editoras que inicializa um vetor vazio.
  public editoras: Array<Editora> = [];

  //Serviços injetados através do construtor.
  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {
    this.livro = new Livro("", 0, "", "", []);
  }
  //Método que preenche o vetor de editoras.
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }
  /*Método incluir que preenche o aributo autores e
  invoca incluir de controle-livros.service.*/
  incluir = (): void => {
    this.livro.autores = this.autoresForm.split("\n").filter(author => author.trim() !== '');
    this.servLivros.incluir(this.livro)
    .then(() => {
      this.router.navigateByUrl("/lista");
    })
  }
}

<main class="container-fluid">
    <!--Título da página.-->
    <h1 class="my-3">
        Dados do livro
    </h1>
    <!--Formulário.-->
    <form (submit)="incluir()" ngNativeValidate>
        <!--Área de título.-->
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" id="titulo" name="titulo" [(ngModel)]="livro.titulo" class="form-control" required>
        </div>
        <!--Área de resumo.-->
        <div class="mb-3">
            <label for="resumo" class="form-label">Resumo</label>
            <textarea id="resumo" name="resumo" [(ngModel)]="livro.resumo" class="form-control" ></textarea>
        </div>
        <!--Área de editora.-->
        <div class="mb-3">
            <label for="editora" class="form-label">Editora</label>
            <select id="editora" name="editora" [(ngModel)]="livro.codEditora" class="form-select" required>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{editora.nome}}</option>
            </select>
        </div>
        <!--Área de autores.-->
        <div class="mb-3">
            <label for="autores" class="form-label">Autores (1 por linha)</label>
            <textarea id="autores" name="autores" [(ngModel)]="autoresForm" class="form-control"></textarea>
        </div>
        <!--Botão para submissão.-->
        <button type="submit" class="btn btn-primary mb-3">Salvar dados</button>
    </form>
</main>
